server:
  port: 8090

spring:
  application:
    name: service-course
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_demo?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: "031214"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# JWT配置
jwt:
  secret: student-management-secret-key-2024
  expiration: 86400000 # 24小时