spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_demo?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: "031214"
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8858
      eager: true