# gateway port
server:
  port: 80

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        import-check:
          enabled: false
    gateway:
      routes:
        - id: service-class
          uri: lb://service-student
          predicates:
            - Path=/classes/**
        - id: service-course
          uri: lb://service-course
          predicates:
            - Path=/course/**
        - id: service-department
          uri: lb://service-department
          predicates:
            - Path=/department/**
        - id: service-login
          uri: lb://service-login
          predicates:
            - Path=/api/**
        - id: service-staff
          uri: lb://service-staff
          predicates:
            - Path=/staff/**
        - id: service-student
          uri: lb://service-student
          predicates:
            - Path=/student/**