# gateway port
server:
  port: 80

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        import-check:
          enabled: false
    gateway:
      routes:
        - id: service-student
          uri: lb://service-student
          predicates:
            - Path=/api/students/**