server:
  port: 8081

spring:
  profiles:
    active: k8s
  application:
    name: service-class
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

feign:
  sentinel:
    enabled: true

# JWT配置
jwt:
  secret: student-management-secret-key-2024
  expiration: 86400000 # 24小时