spring:
  datasource:
    url: jdbc:mysql://192.168.222.130:31840/cloud_demo?characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.222.130:30848
    sentinel:
      transport:
        dashboard: 192.168.222.130:30858
      eager: true